version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    network_mode: host
    environment:
      - USERID=1000
      - GROUPID=1000
    volumes:
      - ./shared:/shared
    command: >
      -w "WORKGROUP"
      -s "shared;/shared;yes;no;yes;all;none;;comment1"
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - 192.168.1.101:80:32400/tcp
    volumes:
      - /opt/plex:/config
      - ./shared/media:/data
    restart: unless-stopped
    hostname: triceratops
    environment:
      - ADVERTISE_IP=http://plex.triceratops.local:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 192.168.1.102:80:9000
    volumes:
      - /opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
       - 192.168.1.98:53:53/udp
       - 192.168.1.98:53:53
       - 192.168.1.98:80:80
    restart: unless-stopped
    cap_add: 
      - NET_ADMIN
    volumes:
      - /opt/pihole/etc/pihole:/etc/pihole
      - /opt/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 8.8.8.8
    environment:
      - ServerIP=192.168.1.100
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
  steamcache:
    image: steamcache/steamcache
    container_name: steamcache 
    restart: unless-stopped
    ports:
      - 192.168.1.99:80:80
    volumes:
      - ./steamcache:/data/cache
      - /opt/steamcache/logs:/data/logs
  origincache:
    image: steamcache/generic:latest
    container_name: origincache
    restart: unless-stopped
    ports:
      - 192.168.1.105:80:80
    volumes:
      - ./origincache:/data/cache
      - /opt/origincache/logs:/data/logs
  origincache-sniproxy:
    image: steamcache/sniproxy
    container_name: origincache-sniproxy 
    restart: unless-stopped
    ports:
      - 192.168.1.105:443:443
  riotcache:
    image: steamcache/generic
    container_name: riotcache 
    restart: unless-stopped
    ports:
      - 192.168.1.104:80:80
    volumes:
      - ./riotcache:/data/cache
      - /opt/riotcache/logs:/data/logs
  riotcache-sniproxy:
    image: steamcache/sniproxy
    container_name: riotcache-sniproxy 
    restart: unless-stopped
    ports:
      - 192.168.1.104:443:443
  steamcache-dns:
    image: steamcache/steamcache-dns
    container_name: steamcache-dns
    restart: unless-stopped
    ports:
      - 192.168.1.99:53:53/udp
      - 192.168.1.99:53:53
    environment:
      - UPSTREAM_DNS=192.168.1.98
      - STEAMCACHE_IP=192.168.1.99
      - RIOTCACHE_IP=192.168.1.104
      - ORIGINCACHE_IP=192.168.1.105
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: triceratops 
    ports:
      - 192.168.1.103:80:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PGID=115
    command: >
      -t 2